# Generated by Django 4.1.7 on 2023-06-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinates',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='coordinates',
            name='mil_image_url',
            field=models.TextField(null=True),
        ),
    ]
